from typing import Dict, List, Any, Protocol
from src.domain.baseline_model import BaselineProfile
from src.domain.task_model import CheckTask
from src.domain.result_model import (
    RecognitionResultSnapshot, RunExecutionSnapshot, RunStatisticsSnapshot,
    IssueAggregateSnapshot, RunSummaryOverview, RecheckDiffSnapshot,
    DeviceReviewContext, ExportArtifact
)

class IBaselineRepository(Protocol):
    def get_all(self) -> List[BaselineProfile]: ...
    def get_by_id(self, baseline_id: str) -> BaselineProfile: ...
    def save(self, profile: BaselineProfile, expected_revision: int = None): ...

class ITaskRepository(Protocol):
    def get_by_id(self, task_id: str) -> CheckTask: ...
    def save(self, task: CheckTask): ...

class IResultRepository(Protocol):
    def save_recognition(self, snap: RecognitionResultSnapshot): ...
    def get_recognition(self, task_id: str) -> RecognitionResultSnapshot: ...
    def save_run_execution(self, snap: RunExecutionSnapshot): ...
    def get_run_execution(self, run_id: str) -> RunExecutionSnapshot: ...
    def save_statistics(self, snap: RunStatisticsSnapshot): ...
    def get_statistics(self, run_id: str) -> RunStatisticsSnapshot: ...
    def save_issue_aggregate(self, snap: IssueAggregateSnapshot): ...
    def get_issue_aggregate(self, run_id: str) -> IssueAggregateSnapshot: ...
    def save_summary(self, summary: RunSummaryOverview): ...
    def get_summary(self, run_id: str) -> RunSummaryOverview: ...
    def save_diff(self, snap: RecheckDiffSnapshot): ...
    def save_review(self, snap: DeviceReviewContext): ...
    def get_diff(self, prev_run_id: str, curr_run_id: str) -> RecheckDiffSnapshot: ...
    def get_review(self, run_id: str, device_name: str) -> DeviceReviewContext: ...
    def save_export(self, snap: ExportArtifact): ...
    def get_exports(self, run_id: str) -> List[ExportArtifact]: ...

class IExcelReader(Protocol):
    def read(self, file_path: str) -> Dict[str, Any]: ...
